const state={screen:'home',detail:null,playerX:260,vel:0,onGround:true,keys:{},stageX:0};const world=document.getElementById('world'),home=document.getElementById('home'),detail=document.getElementById('detail'),about=document.getElementById('about'),lab=document.getElementById('lab'),menu=document.getElementById('menu'),stage=document.getElementById('worldStage'),player=document.getElementById('player');
const order=Object.keys(PROJECTS);const positions={tokyo:900,yuyu:1900,youyan:2900,tianyou:3900,banana:4900,tencent:5900,archive:6900};
function hideAll(){[home,world,detail,about,lab].forEach(x=>x.classList.add('hidden'));menu.classList.add('hidden')}
function showHome(){hideAll();home.classList.remove('hidden');state.screen='home'}
function showWorld(){hideAll();world.classList.remove('hidden');state.screen='world';state.detail=null;requestAnimationFrame(loop)}
function makeWorld(){const box=document.getElementById('worldItems');box.innerHTML='';order.forEach((k,i)=>{const p=PROJECTS[k],el=document.createElement('button');el.className='world-sign';el.style.left=positions[k]+'px';el.innerHTML=`<img class="cover" src="${p.cover}"><div class="num">PROJECT ${String(i+1).padStart(2,'0')}</div><h3>${p.title}</h3><p>${p.cn} · ${p.desc}</p>`;el.addEventListener('click',()=>openProject(k));box.appendChild(el)});const a=document.createElement('button');a.className='world-sign';a.style.left='7750px';a.innerHTML='<div class="num">INFO</div><h3>ABOUT ECHO</h3><p>Profile / Experience</p>';a.addEventListener('click',()=>showAbout());box.appendChild(a)}
function openProject(k){state.detail=k;hideAll();detail.classList.remove('hidden');const p=PROJECTS[k];document.getElementById('detailIndex').textContent='PROJECT '+String(order.indexOf(k)+1).padStart(2,'0')+' / '+String(order.length).padStart(2,'0');document.getElementById('detailEyebrow').textContent=p.cn+' · '+p.desc;document.getElementById('detailTitle').textContent=p.title;document.getElementById('detailDesc').textContent='Selected work from the current archive. More complete case-study context can be added as the portfolio develops.';const g=document.getElementById('detailGallery');g.innerHTML='';p.images.forEach(src=>{const im=document.createElement('img');im.src=src;im.loading='lazy';im.onload=()=>{if(im.naturalHeight>im.naturalWidth*1.35) im.classList.add('tall');};g.appendChild(im)})}
function showAbout(){hideAll();about.classList.remove('hidden');state.screen='about'}function showLab(){hideAll();lab.classList.remove('hidden');state.screen='lab'}
document.getElementById('enterBtn').onclick=showWorld;document.getElementById('homeBtn').onclick=showHome;document.getElementById('worldBtn').onclick=showWorld;document.getElementById('backWorld').onclick=showWorld;document.querySelectorAll('.genericBack').forEach(b=>b.onclick=showWorld);document.getElementById('menuBtn').onclick=()=>menu.classList.remove('hidden');document.getElementById('menuClose').onclick=()=>menu.classList.add('hidden');document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{menu.classList.add('hidden');({home:showHome,world:showWorld,about:showAbout,lab:showLab}[b.dataset.menu])()});
function nearest(){let best=null,dist=Infinity;for(const k of order){const d=Math.abs(state.playerX-positions[k]);if(d<dist){dist=d;best=k}}return dist<260?best:null}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space','KeyA','KeyD','KeyE'].includes(e.code))e.preventDefault();state.keys[e.code]=true;if(e.code==='KeyE'&&state.screen==='world'){const k=nearest();if(k)openProject(k)}if(e.code==='Escape'){if(state.screen==='world')showHome();else if(state.screen==='home'){}else showWorld()}});window.addEventListener('keyup',e=>state.keys[e.code]=false);
document.querySelectorAll('.mobile-controls button').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',()=>{if(k==='left')state.keys.ArrowLeft=true;if(k==='right')state.keys.ArrowRight=true;if(k==='jump')state.keys.Space=true;if(k==='enter'){const n=nearest();if(n)openProject(n)}});b.addEventListener('pointerup',()=>{if(k==='left')state.keys.ArrowLeft=false;if(k==='right')state.keys.ArrowRight=false;if(k==='jump')state.keys.Space=false})});
let last=performance.now();function loop(now){if(state.screen!=='world')return;const dt=Math.min(.033,(now-last)/1000);last=now;const left=state.keys.ArrowLeft||state.keys.KeyA,right=state.keys.ArrowRight||state.keys.KeyD;if(left)state.vel-=900*dt;if(right)state.vel+=900*dt;if(!left&&!right)state.vel*=Math.pow(.0008,dt);state.vel=Math.max(-420,Math.min(420,state.vel));state.playerX+=state.vel*dt;if(state.playerX<120)state.playerX=120;if(state.playerX>7200)state.playerX=7200;if(state.keys.Space&&state.onGround){state.onGround=false;state.jumpV=650;state.keys.Space=false}if(!state.onGround){state.jumpV-=1700*dt;state.playerY=(state.playerY||0)+state.jumpV*dt;if(state.playerY<=0){state.playerY=0;state.onGround=true;state.jumpV=0}}const camera=Math.max(0,Math.min(6800,state.playerX-360));stage.style.transform=`translateX(${-camera}px)`;player.style.transform=`translate(${state.playerX}px,${-state.playerY}px)`;requestAnimationFrame(loop)}
makeWorld();showHome();