const projects={
 youyan:{no:'01',title:'YOUYAN',kicker:'2025—NOW / GUANGZHOU YOUYAN GAMES',type:'Visual Lead / Publishing',role:'平面主管',markets:'Europe · MENA · Korea',scope:'Visual direction · Publishing · UA creative',summary:'Current chapter. Visual planning and publishing direction across multiple game projects, with a focus on market-facing creative and performance feedback.',outcomes:['统筹项目平面视觉需求与设计规划。','结合投放数据与市场趋势规划平面素材方向。','负责发行角色设定、主视觉及各类界面视觉需求。','持续迭代素材方向，并以实际消耗结果验证创意。'],gallery:[]},
 tokyo:{no:'02',title:'Tokyo Ghoul',kicker:'2024—2025 / HULAI GAMES',type:'IP Publishing Campaign',role:'Visual Lead / Publishing Design',markets:'Korea · International',scope:'Campaign visual · Store · H5 · PC page · UA-facing creative',summary:'An IP-driven publishing case. The work balances recognizable IP language with performance-oriented communication across store, H5 and campaign surfaces.',outcomes:['Coordinated the visual requirements from brief through delivery.','Covered campaign visuals, store assets, H5 and PC promotional surfaces.','Worked with marketing and external production partners through design review and delivery.'],gallery:[['assets/works/hula-tokyo-ghoul/01-K.jpg','Main key visual'],['assets/works/hula-tokyo-ghoul/02.jpg','Store / campaign'],['assets/works/hula-tokyo-ghoul/03.jpg','Store / campaign'],['assets/works/hula-tokyo-ghoul/04.jpg','Store / campaign'],['assets/works/hula-tokyo-ghoul/05.jpg','Store / campaign'],['assets/works/hula-tokyo-ghoul/06.jpg','Store / campaign'],['assets/works/hula-tokyo-ghoul/H5--1.jpg','H5 page'],['assets/works/hula-tokyo-ghoul/PC--1.jpg','PC page']]},
 yuyu:{no:'03',title:'Yu Yu Hakusho',kicker:'2024—2025 / HULAI GAMES',type:'IP Publishing Campaign',role:'Visual Lead / Publishing Design',markets:'Korea · International',scope:'Campaign visual · Store · H5 · PC page',summary:'A second IP publishing case from the same studio period, showing the ability to adapt a common publishing workflow to a very different IP visual language.',outcomes:['Planned and followed visual requirements through delivery.','Produced campaign, store and H5/PC promotional materials.','Coordinated external design resources and reviewed output against product needs.'],gallery:[['assets/works/hula-yuyu-hakusho/01--.jpg','Main visual'],['assets/works/hula-yuyu-hakusho/02----.jpg','Campaign visual'],['assets/works/hula-yuyu-hakusho/03--.jpg','Campaign visual'],['assets/works/hula-yuyu-hakusho/04--.jpg','Campaign visual'],['assets/works/hula-yuyu-hakusho/05--.jpg','Campaign visual'],['assets/works/hula-yuyu-hakusho/06--.jpg','Campaign visual'],['assets/works/hula-yuyu-hakusho/H5--.jpg','H5 page'],['assets/works/hula-yuyu-hakusho/PC--.jpg','PC page']]},
 fatxiyou:{no:'04',title:'胖西游',kicker:'2024 / TIANYOU NETWORK',type:'Product Visual',role:'Game Visual Designer',markets:'Hong Kong · Macao · Taiwan',scope:'Key visual · Store assets · Logo · Icon',summary:'A product-visual project built around a playful, high-recognition art direction. The case demonstrates how a coherent visual language is extended across store communication.',outcomes:['Translated product characteristics into a consistent visual direction.','Produced store and promotional assets with clear gameplay / feature communication.','Built a reusable visual language across a set of commercial touchpoints.'],gallery:[['assets/works/tianyou-fat-xiyou/1920-1080-00.jpg','Store visual'],['assets/works/tianyou-fat-xiyou/1920-1080-01.jpg','Feature visual'],['assets/works/tianyou-fat-xiyou/1920-1080-02.jpg','Feature visual'],['assets/works/tianyou-fat-xiyou/1920-1080-03.jpg','Feature visual'],['assets/works/tianyou-fat-xiyou/1920-1080-04.jpg','Feature visual'],['assets/works/tianyou-fat-xiyou/1920-1080-05.jpg','Feature visual']]},
 banana:{no:'05',title:'Digital Girls',kicker:'2022—2023 / BANANA INTERACTIVE',type:'Game Publishing Visual',role:'Game Visual Designer',markets:'Game publishing',scope:'KV · Store assets · Icon · Reservation page · AI-assisted asset creation',summary:'A publishing-focused period where visual design moved closer to market communication: identify selling points, translate them into creative, then iterate with the market team.',outcomes:['Designed key visuals, store assets, icons and reservation-page materials.','Worked with marketing to identify selling points and iterate creative toward stronger conversion.','Used AI-assisted image generation to build a reusable visual asset pool for UA creative.'],gallery:[['assets/works/banana-digital-girls/01.jpg','Store visual'],['assets/works/banana-digital-girls/02.jpg','Gameplay / feature'],['assets/works/banana-digital-girls/03.jpg','System / feature'],['assets/works/banana-digital-girls/jpg-00--.jpg','Main visual'],['assets/works/banana-digital-girls/jpg-01--.jpg','Character visual'],['assets/works/banana-digital-girls/jpg-02--.jpg','Character visual']]},
 start:{no:'06',title:'START',kicker:'2020—2022 / TENCENT START',type:'Brand / Product Visual',role:'Game Visual Designer',markets:'China / Cloud Gaming',scope:'Platform packaging · H5 · PC operations',summary:'A product-side chapter focused on the visual packaging of Tencent START Cloud Gaming and the complete delivery loop from design to development and launch.',outcomes:['Owned H5 / PC campaign-page design, slicing, annotation and developer handoff.','Followed post-launch click performance and collaborated with operations and development to improve outcomes.','Helped establish and refine product visual / brand-operation standards.'],gallery:[['assets/works/tencent-start/13--.png','Platform / brand'],['assets/works/tencent-start/PC-.jpg','Campaign page'],['assets/works/tencent-start/PC.jpg','Game campaign']]},
 foundation:{no:'07',title:'Foundation',kicker:'2019—2020 / JIU ZUO CULTURE',type:'Game Visual Design',role:'Independent Visual Designer',markets:'Tencent game ecosystem',scope:'Honor of Kings · Peace Elite · Blade & Soul',summary:'The foundation era: independent visual production across major Tencent game campaigns. This period established the visual craft, delivery discipline and ability to translate game IP into campaign-ready assets.',outcomes:['Independent ownership of visual design for multiple Tencent game-related projects.','Experience spanning KV, character/campaign visuals and promotional pages.','Built the production habits that later scaled into publishing and team coordination.'],gallery:[['assets/works/jiuzuo-and-other/KV.jpg','Campaign KV'],['assets/works/jiuzuo-and-other/EN.jpg','Content campaign'],['assets/works/jiuzuo-and-other/KK----K.png','Esports / Warcraft key visual'],['assets/works/jiuzuo-and-other/KK---FoCuS.png','Character visual'],['assets/works/jiuzuo-and-other/KK---LawLiet.png','Character visual'],['assets/works/jiuzuo-and-other/KK---lyn.png','Character visual']]}
};
const career=[['2025—NOW','广州游雁游戏','平面主管','Blue Sky · Xuan Ying · V5 · QV1 · F2'],['2024—2025','广州胡莱游戏','平面主管','Tokyo Ghoul · Yu Yu Hakusho'],['2024','广州天游网络科技有限公司','游戏视觉设计师','胖西游 · 轮回双生 · 超级拳霸霸'],['2022—2023','广州香蕉互娱科技有限公司','游戏视觉设计师','Digital Girls / publishing projects'],['2020—2022','腾讯 START 云游戏','游戏视觉设计师','Brand · H5 · PC operations'],['2019—2020','深圳市玖作文化传播有限公司','游戏视觉设计师','王者荣耀 · 和平精英 · 剑灵']];
const i18n={
 'zh-CN':{label:'中',nav:{projects:'作品',about:'关于我'},intro:{eyebrow:'游戏视觉设计师 / 2019—至今',sub:'游戏视觉设计、发行视觉与 IP 宣发。',enterWorld:'进入我的世界',browse:'浏览作品',micro:'一个可以玩的个人作品集。'},game:{title:'走进我的作品。',mobile:'滑动探索 · 点击传送门',enter:'进入项目'},panel:{selected:'精选作品',projects:'作品集',projectsDesc:'从最近、最成熟的阶段开始，向前回看完整职业成长。',about:'关于 Echo',aboutTitle:'游戏视觉设计师',career:'职业经历 / 最近 → 过去',owned:'负责内容',selectedWork:'精选作品',current:'当前工作',currentText:'当前阶段的公开作品会在确认可以展示后补充。',metrics:'成果数据',metricsText:'后续只加入经过验证的数据：投放消耗、CTR/CVR、素材产量、项目数量、交付周期、外包规模、团队规模与市场数量。'}},
 'zh-TW':{label:'繁',nav:{projects:'作品',about:'關於我'},intro:{eyebrow:'遊戲視覺設計師 / 2019—至今',sub:'遊戲視覺設計、發行視覺與 IP 宣發。',enterWorld:'進入我的世界',browse:'瀏覽作品',micro:'一個可以玩的個人作品集。'},game:{title:'走進我的作品。',mobile:'滑動探索 · 點擊傳送門',enter:'進入專案'},panel:{selected:'精選作品',projects:'作品集',projectsDesc:'從最近、最成熟的階段開始，向前回看完整職涯成長。',about:'關於 Echo',aboutTitle:'遊戲視覺設計師',career:'職涯經歷 / 最近 → 過去',owned:'負責內容',selectedWork:'精選作品',current:'目前工作',currentText:'目前階段的公開作品會在確認可以展示後補充。',metrics:'成果數據',metricsText:'後續只加入經過驗證的數據：投放消耗、CTR/CVR、素材產量、專案數量、交付週期、外包規模、團隊規模與市場數量。'}},
 'en':{label:'EN',nav:{projects:'PROJECTS',about:'ABOUT'},intro:{eyebrow:'GAME VISUAL DESIGNER / 2019—NOW',sub:'Game visual design, publishing and IP campaigns.',enterWorld:'ENTER MY WORLD',browse:'BROWSE WORK',micro:'A playable portfolio by Echo Wang.'},game:{title:'Walk through my work.',mobile:'Swipe to explore · tap a portal',enter:'ENTER PROJECT'},panel:{selected:'SELECTED WORK',projects:'PROJECTS',projectsDesc:'Start with the newest, strongest work and move backward through the career.',about:'ABOUT ECHO',aboutTitle:'GAME VISUAL DESIGNER',career:'CAREER / RECENT → PAST',owned:'MY ROLE',selectedWork:'SELECTED WORK',current:'CURRENT WORK',currentText:'Current public work will be added once it is cleared for presentation.',metrics:'RESULTS TO ADD',metricsText:'Only verified numbers will be added: spend, CTR/CVR, asset volume, project count, delivery time, outsourcing scale, team size and markets.'}},
 'ko':{label:'한',nav:{projects:'작품',about:'소개'},intro:{eyebrow:'게임 비주얼 디자이너 / 2019—현재',sub:'게임 비주얼 디자인, 퍼블리싱 및 IP 캠페인.',enterWorld:'나의 세계로',browse:'작품 보기',micro:'Echo Wang의 플레이 가능한 포트폴리오.'},game:{title:'나의 작업을 직접 걸어보세요.',mobile:'스와이프하여 탐색 · 포털을 탭하세요',enter:'프로젝트 보기'},panel:{selected:'주요 작업',projects:'작품집',projectsDesc:'가장 최근의 성숙한 작업부터 시작해 커리어의 흐름을 거꾸로 살펴봅니다.',about:'Echo 소개',aboutTitle:'게임 비주얼 디자이너',career:'경력 / 최근 → 과거',owned:'담당 업무',selectedWork:'주요 작업',current:'현재 작업',currentText:'공개 가능한 현재 프로젝트는 확인 후 추가합니다.',metrics:'성과 데이터',metricsText:'검증된 데이터만 추가합니다: 광고 집행액, CTR/CVR, 제작 수량, 프로젝트 수, 납기, 외주 규모, 팀 규모 및 시장 수.'}}
};
const translations={};
translations['zh-CN']={
 youyan:{type:'视觉主管 / 游戏发行',role:'平面主管',markets:'欧洲 · 中东 · 韩国',scope:'视觉方向 · 发行 · UA 创意',summary:'当前职业阶段。负责多个游戏项目的发行视觉规划与平面统筹，关注市场传播、素材方向与投放反馈。',outcomes:['统筹项目平面视觉需求与设计规划。','结合投放数据与市场趋势规划平面素材方向。','负责发行角色设定、主视觉及各类视觉需求。','持续迭代素材方向，并以实际消耗结果验证创意。']},
 tokyo:{type:'IP 发行视觉',role:'视觉负责人 / 发行设计',markets:'韩国 · 海外',scope:'宣发视觉 · 商店 · H5 · PC 页面 · UA 素材',summary:'以 IP 为核心的发行案例，在保持 IP 识别度的同时，将市场传播效率融入商店、H5 与活动页面。',outcomes:['统筹从需求到交付的视觉工作。','覆盖宣发主视觉、商店、H5 与 PC 宣传页面。','与市场及外部制作资源协作，完成设计审核与交付。']},
 yuyu:{type:'IP 发行视觉',role:'视觉负责人 / 发行设计',markets:'韩国 · 海外',scope:'宣发视觉 · 商店 · H5 · PC 页面',summary:'同一发行阶段的第二个 IP 案例，体现将成熟的发行流程适配到不同 IP 视觉语言的能力。',outcomes:['规划并跟进视觉需求直至交付。','完成宣发、商店与 H5 / PC 宣传素材。','协调外部设计资源并根据产品需求进行审核。']},
 fatxiyou:{type:'产品视觉',role:'游戏视觉设计师',markets:'港澳台',scope:'主视觉 · 商店素材 · Logo · Icon',summary:'围绕高识别度、轻松的产品调性建立视觉方向，并将其延展到商业化触点。',outcomes:['将产品特点转化为统一的视觉方向。','制作商店及宣传素材，清晰传达玩法与卖点。','建立可复用的商业化视觉语言。']},
 banana:{type:'游戏发行视觉',role:'游戏视觉设计师',markets:'游戏发行',scope:'KV · 商店 · Icon · 预约页 · AI 辅助素材',summary:'视觉设计进一步贴近市场传播：提炼卖点、转化为创意，再与市场团队根据反馈持续迭代。',outcomes:['完成 KV、商店、Icon 与预约页等发行视觉。','与市场团队提炼卖点并调整创意方向。','使用 AI 辅助建立可复用的视觉素材池。']},
 start:{type:'品牌 / 产品视觉',role:'游戏视觉设计师',markets:'中国 · 云游戏',scope:'平台包装 · H5 · PC 运营',summary:'围绕腾讯 START 云游戏的产品视觉包装，经历从设计、切图标注到开发上线的完整交付流程。',outcomes:['负责 H5 / PC 活动页设计、切图、标注与开发交付。','关注上线后的点击表现，与运营、开发协作优化。','参与产品视觉与品牌运营规范的建立和迭代。']},
 foundation:{type:'游戏视觉设计',role:'独立视觉设计师',markets:'腾讯游戏生态',scope:'王者荣耀 · 和平精英 · 剑灵',summary:'职业早期的视觉基础阶段，独立完成多个游戏相关项目，建立设计、交付与 IP 转化能力。',outcomes:['独立负责多个游戏相关项目的视觉设计。','覆盖 KV、角色 / 活动视觉与宣传页面。','建立后来扩展到发行与团队协作的制作和交付能力。']}
};
translations['zh-TW']=translations['zh-CN'];
translations['en']=projects;
translations['ko']=projects;
const intro=document.getElementById('intro'),game=document.getElementById('game'),track=document.getElementById('worldTrack'),bg=document.getElementById('worldBackground'),platformsEl=document.getElementById('platforms'),portalsEl=document.getElementById('portals'),player=document.getElementById('player'),viewport=document.getElementById('gameViewport'),progressFill=document.getElementById('progressFill'),nearHint=document.getElementById('nearHint'),panel=document.getElementById('panel'),panelContent=document.getElementById('panelContent'),panelIndex=document.getElementById('panelIndex'),toast=document.getElementById('toast');
let lang=localStorage.getItem('echo-lang')||'zh-CN', worldWidth=0, segmentWidth=0, playerX=280,playerY=0,vx=0,vy=0,grounded=true,keys={},last=performance.now(),touchStart=null,currentPortal=null;
const portalData=[['youyan',.08],['tokyo',.205],['yuyu',.33],['fatxiyou',.46],['banana',.60],['start',.74],['foundation',.88]];
function T(path){return path.split('.').reduce((o,k)=>o?.[k],i18n[lang])||path}
function applyLanguage(l){lang=l;localStorage.setItem('echo-lang',l);document.documentElement.lang=l;document.body.dataset.lang=l;document.getElementById('langButton').innerHTML=`${i18n[l].label} <span>⌄</span>`;document.querySelectorAll('.lang-menu button').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=T(el.dataset.i18n));if(panel.classList.contains('open')){const view=panel.dataset.view;if(view==='projects')openProjects();else if(view==='about')openAbout();else if(view==='project')openProject(panel.dataset.project)}}
function buildWorld(){bg.innerHTML='';const h=window.innerHeight;segmentWidth=Math.max(1600,Math.round(2016*h/864));worldWidth=segmentWidth*4;track.style.width=worldWidth+'px';for(let i=0;i<4;i++){const s=document.createElement('div');s.className='bg-segment'+(i%2?' flip':'');s.style.width=segmentWidth+'px';bg.appendChild(s)}
platformsEl.innerHTML='';[{x:.16,w:220,h:62},{x:.38,w:280,h:95},{x:.57,w:230,h:72},{x:.81,w:260,h:110}].forEach(p=>{const el=document.createElement('div');el.className='platform';el.style.left=(p.x*worldWidth)+'px';el.style.bottom=(15.5+p.h/8)+'%';el.style.width=p.w+'px';el.style.height='12px';platformsEl.appendChild(el)});
portalsEl.innerHTML='';portalData.forEach(([key,ratio])=>{const p=projects[key],el=document.createElement('button');el.className='portal';el.dataset.project=key;el.style.left=(ratio*worldWidth)+'px';el.innerHTML=`<span class="portal-frame"></span><span class="portal-base"></span><span class="portal-label"><small class="portal-no">${p.no}</small><strong class="portal-title">${p.title}</strong><small class="portal-year">${p.kicker.split(' / ')[0]}</small></span>`;el.addEventListener('click',()=>openProject(key));portalsEl.appendChild(el)});playerX=Math.max(240,Math.min(worldWidth*.03,420));playerY=0;vx=0;vy=0;}
function enterWorld(){intro.classList.add('hidden');game.classList.add('active');game.setAttribute('aria-hidden','false');setTimeout(()=>{buildWorld();viewport.focus();showToast(T('game.enter')+' · ← → · SPACE')},40)}
function home(){closePanel();game.classList.remove('active');intro.classList.remove('hidden');game.setAttribute('aria-hidden','true')}
function move(dir){vx+=dir*1600/60;vx=Math.max(-420,Math.min(420,vx));player.dataset.face=dir<0?'left':'right'}
function jump(){if(!grounded)return;vy=-720;grounded=false;player.classList.add('jump');setTimeout(()=>player.classList.remove('jump'),260)}
function nearest(){let best=null,dist=Infinity;document.querySelectorAll('.portal').forEach(p=>{const x=parseFloat(p.style.left);const d=Math.abs(x-playerX);p.classList.toggle('near',d<135);if(d<dist){dist=d;best=p}});return dist<145?best:null}
function update(dt){const left=keys.ArrowLeft||keys.a||keys.A,right=keys.ArrowRight||keys.d||keys.D;if(left)move(-1);if(right)move(1);if(!left&&!right)vx*=Math.pow(.0005,dt);else vx*=Math.pow(.08,dt);vy+=2050*dt;playerX+=vx*dt;playerY+=vy*dt;const groundY=0;if(playerY>=groundY){playerY=groundY;vy=0;grounded=true}else grounded=false;playerX=Math.max(170,Math.min(worldWidth-180,playerX));
const cam=Math.max(0,Math.min(worldWidth-window.innerWidth,playerX-window.innerWidth*.37));track.style.transform=`translate3d(${-cam}px,0,0)`;player.style.left=playerX+'px';player.style.bottom='14%';player.classList.toggle('walk',Math.abs(vx)>45&&grounded);const t=(playerX-170)/(worldWidth-350);progressFill.style.width=Math.max(0,Math.min(100,t*100))+'%';const n=nearest();currentPortal=n?.dataset.project||null;nearHint.classList.toggle('show',!!n);if(n)nearHint.querySelector('span').textContent=(window.innerWidth<700?T('game.enter'):'E  '+T('game.enter'));}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(game.classList.contains('active')&&!panel.classList.contains('open'))update(dt);requestAnimationFrame(loop)}
function showToast(s){toast.textContent=s;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function openPanel(){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}
function closePanel(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function openProject(key){const p=projects[key],t=translations[lang][key]||translations['en'][key];panel.dataset.view='project';panel.dataset.project=key;panelIndex.textContent=`${p.no} / ${t.type.toUpperCase()}`;document.getElementById('panelLocation').textContent=p.kicker;panelContent.innerHTML=`<div class="panel-kicker">${p.kicker}</div><h2>${p.title}</h2><p class="panel-lead">${t.summary}</p><div class="meta-grid"><div><span>ROLE</span><b>${t.role}</b></div><div><span>TYPE</span><b>${t.type}</b></div><div><span>MARKET / SCOPE</span><b>${t.markets}<br>${t.scope}</b></div></div><h3 class="panel-section-title">${i18n[lang].panel.owned}</h3><div class="outcomes">${t.outcomes.map(x=>`<div class="outcome">${x}</div>`).join('')}</div>${p.gallery.length?`<h3 class="panel-section-title">${i18n[lang].panel.selectedWork}</h3><div class="gallery">${p.gallery.map((g,i)=>`<figure><img src="${g[0]}" alt="${g[1]}" loading="${i?'lazy':'eager'}"><figcaption>${g[1]}</figcaption></figure>`).join('')}</div>`:`<h3 class="panel-section-title">${i18n[lang].panel.current}</h3><div class="data-note">${i18n[lang].panel.currentText}</div>`}`;openPanel()}
function openProjects(){panel.dataset.view='projects';panelIndex.textContent='00 / '+i18n[lang].panel.selected.toUpperCase();document.getElementById('panelLocation').textContent='ECHO WORLD';const list=portalData.map(([k])=>projects[k]);panelContent.innerHTML=`<div class="panel-kicker">${i18n[lang].panel.selected}</div><h2>${i18n[lang].panel.projects}</h2><p class="panel-lead">${i18n[lang].panel.projectsDesc}</p><div class="project-list">${list.map(p=>`<div class="project-row" data-key="${Object.keys(projects).find(k=>projects[k]===p)}"><b>${p.no}</b><strong>${p.title}</strong><small>${p.kicker.split(' / ')[0]}</small></div>`).join('')}</div>`;openPanel();panelContent.querySelectorAll('.project-row').forEach(r=>r.onclick=()=>openProject(r.dataset.key))}
function openAbout(){panel.dataset.view='about';panelIndex.textContent='ABOUT / ECHO WANG';document.getElementById('panelLocation').textContent='CAREER / RECENT → PAST';panelContent.innerHTML=`<div class="panel-kicker">${i18n[lang].panel.about}</div><h2>${i18n[lang].panel.aboutTitle}</h2><p class="panel-lead">Echo Wang — Game Visual Designer, with experience across game visual design, publishing, IP campaigns and product communication.</p><h3 class="panel-section-title">${i18n[lang].panel.career}</h3><div class="career-list">${career.map(c=>`<div class="career-item"><time>${c[0]}</time><div><h4>${c[1]}</h4><p>${c[2]}</p></div><p>${c[3]}</p></div>`).join('')}</div><h3 class="panel-section-title">${i18n[lang].panel.metrics}</h3><div class="data-note">${i18n[lang].panel.metricsText}</div>`;openPanel()}

document.getElementById('enterBtn').onclick=enterWorld;document.getElementById('browseBtn').onclick=()=>{enterWorld();setTimeout(openProjects,80)};document.getElementById('brandHome').onclick=home;document.getElementById('worldBtn').onclick=enterWorld;document.getElementById('projectsBtn').onclick=()=>{if(!game.classList.contains('active'))enterWorld();setTimeout(openProjects,80)};document.getElementById('aboutBtn').onclick=()=>{if(!game.classList.contains('active'))enterWorld();setTimeout(openAbout,80)};document.getElementById('mapBtn').onclick=openProjects;document.getElementById('gameAboutBtn').onclick=openAbout;document.querySelectorAll('[data-close]').forEach(e=>e.onclick=closePanel);
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space'].includes(e.key))e.preventDefault();keys[e.key]=true;keys[e.key.toLowerCase()]=true;if(e.code==='Space'){e.preventDefault();jump()}if(e.key.toLowerCase()==='e'&&currentPortal)openProject(currentPortal);if(e.key==='Escape')closePanel()});document.addEventListener('keyup',e=>{keys[e.key]=false;keys[e.key.toLowerCase()]=false});
document.querySelectorAll('.mobile-controls button').forEach(b=>{const action=b.dataset.control;const key=action==='left'?'ArrowLeft':action==='right'?'ArrowRight':'Space';const on=e=>{e.preventDefault();if(action==='jump')jump();else keys[key]=true};const off=e=>{e.preventDefault();if(action!=='jump')keys[key]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
viewport.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchStart=e.clientX});viewport.addEventListener('pointermove',e=>{if(touchStart===null)return;const dx=e.clientX-touchStart;if(Math.abs(dx)>14){move(dx>0?1:-1);touchStart=e.clientX}});viewport.addEventListener('pointerup',()=>touchStart=null);viewport.addEventListener('pointercancel',()=>touchStart=null);
const langButton=document.getElementById('langButton'),langMenu=document.getElementById('langMenu');langButton.onclick=e=>{e.stopPropagation();langMenu.classList.toggle('open');langButton.setAttribute('aria-expanded',langMenu.classList.contains('open'))};langMenu.querySelectorAll('button').forEach(b=>b.onclick=()=>{applyLanguage(b.dataset.lang);langMenu.classList.remove('open');langButton.setAttribute('aria-expanded','false')});document.addEventListener('click',()=>langMenu.classList.remove('open'));window.addEventListener('resize',()=>{if(game.classList.contains('active'))buildWorld()});
applyLanguage(lang);requestAnimationFrame(loop);
